### ISSUE TITLE
Error:operands could not be broadcast together with shapes (7,6) (7,7) 

### ISSUE THREAD

**Issue by OOXXXXOO** [ahmedfgad/NumPyCNN#1] opened 2018-05-13 10:05 UTC
When i run this code have a error that is "operands could not be broadcast together with shapes (7,6) (7,7) "

**Comment by lomenie** [comment] 2018-05-13 13:59
I ve got the same....

**Comment by lomenie** [comment] 2018-05-22 03:49
no answer from the developer ?

**Comment by ahmedfgad** [comment] 2018-05-22 12:03
Thanks for your note.
The shared code is running fine with me and some other people. This is why I got confused of it.
But after investigating the code well, I figured out the source the error and I am planning to work on the code and solve it in the next few days.
Thanks again.

**Comment by ahmedfgad** [comment] 2018-05-24 13:28
The issue is fixed. The issue was due to incompatibility of shape between the filter and the image region being worked on. It is solved based on such lines:

```python
curr_region = img[r-numpy.uint16(numpy.floor(filter_size/2)):r+numpy.uint16(numpy.ceil(filter_size/2)), 
                              c-numpy.uint16(numpy.floor(filter_size/2)):c+numpy.uint16(numpy.ceil(filter_size/2))]
```

**Comment by lomenie** [comment] 2018-05-24 13:34
Thanks but it means that some version of python or numpy are not sensitive to the type issue right?

Nicolas Lomenie

**Comment by ahmedfgad** [comment] 2018-05-24 13:55
Yes this is the reason.
The code is running in my PC without error. The same code gives an error on another without changing any part.
At all, the version of Python and NumPy I used are as follows:
**The project is tested using Python 3.5.2 installed inside Anaconda 4.2.0 (64-bit)
NumPy version used is 1.14.0**

**Comment by lomenie** [comment] 2018-05-27 07:26
Thanks but still  an issue
*Working with conv layer 1**
('Filter ', 1)
Traceback (most recent call last):
  File "example.py", line 44, in <module>
    l1_feature_map = numpycnn.conv(img, l1_filter)
  File "/Users/lomenie/Documents/GitHub/NumPyCNN/numpycnn.py", line 78, in conv
    conv_map = conv_(img, curr_filter)
  File "/Users/lomenie/Documents/GitHub/NumPyCNN/numpycnn.py", line 38, in conv_
    curr_result = curr_region * conv_filter
ValueError: operands could not be broadcast together with shapes (2,2) (3,3)

**Comment by lomenie** [comment] 2018-05-28 05:55
With the first code here is the pb (so I do not think it is a uint type issue)
**Working with conv layer 1**
('Filter ', 1)
Filter Size
3
('Filter ', 2)
Filter Size
3

**ReLU**

**Pooling**
**End of conv layer 1**


**Working with conv layer 2**
('Filter ', 1)
Filter Size
5
Filter Size
5
('Filter ', 2)
Filter Size
5
Filter Size
5
('Filter ', 3)
Filter Size
5
Filter Size
5

**ReLU**

**Pooling**
**End of conv layer 2**


**Working with conv layer 3**
('Filter ', 1)
Filter Size
7
Traceback (most recent call last):
  File "NumPyCNN.py", line 129, in <module>
    l3_feature_map = conv(l2_feature_map_relu_pool, l3_filter)
  File "NumPyCNN.py", line 58, in conv
    conv_map = conv_(img[:, :, 0], curr_filter[:, :, 0]) # Array holding the sum of all feature maps.
  File "NumPyCNN.py", line 23, in conv_
    curr_result = curr_region * conv_filter
ValueError: operands could not be broadcast together with shapes (7,6) (7,7)

**Comment by ahmedfgad** [comment] 2018-05-30 22:43
I am very thankful for your notes.
You are right. The bug still exist.
I figured a fault that may causing such error after running such code on another device with another version of NumPy.
I figured out that the numpy.ceil was not working correctly. When I run this line,
```python
numpy.uint16(numpy.ceil(3/2))
```
The expected output is 2 but it returns 1. Due to dividing two integers (3 and 2), the result will also be an integer (1). The ceil of that integer is 1.
Based on that, the region size is calculated based on the following code will be always smaller than the filter size:
```python
            curr_region = img[r-numpy.uint16(numpy.floor(filter_size/2)):r+numpy.uint16(numpy.ceil(filter_size/2)), 
                              c-numpy.uint16(numpy.floor(filter_size/2)):c+numpy.uint16(numpy.ceil(filter_size/2))]
```
This bug is fixed by making one of the two numbers float. For example, numpy.ceil(filter_size/2.0). The previous code will be as follows:
```python
curr_region = img[r-numpy.uint16(numpy.floor(filter_size/2.0)):r+numpy.uint16(numpy.ceil(filter_size/2.0)), c-numpy.uint16(numpy.floor(filter_size/2.0)):c+numpy.uint16(numpy.ceil(filter_size/2.0))]
```

**Comment by ahmedfgad** [comment] 2020-05-20 09:54
The issue is closed for being solved.

**Closed as completed by ahmedfgad** 2020-05-20 09:54 UTC
Labels: bug
